# -*- coding: utf-8 -*-
"""Projeto portifolio 3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Pp0JVhXIagbvWDiop0lA5WqSg8MbhKis

Aqui vamos analisar um dataset de 20 funcionarios de uma empresa

objetivo:


*   Analisar quais funcionarios estão com **férias em dia** e **férias vencidas**
*   Analisar o **impacto** financeiro que os funcionarios com férias vencidas pode gerar para a empresa
*   Analisar quais setores tem mais funcionarios com **ferias vencidas**
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

ferias = pd.read_csv('/content/drive/MyDrive/curriculos/dataset/dataset_funcionarios_veman.csv')
ferias.head(5)

"""**Ferias em dia**"""

ferias[ferias['anos_ferias_vencidas'] == 0].groupby(['nome','setor'])['anos_ferias_vencidas'].sum()

"""**Ferias vencidas**"""

ferias[ferias['anos_ferias_vencidas'] > 0].groupby(['nome','cargo'])['anos_ferias_vencidas'].sum().sort_values(ascending=False)

ferias[ferias['anos_ferias_vencidas'] > 0].groupby(['nome','cargo'])['anos_ferias_vencidas'].sum().sort_values(ascending=False)

"""vamos calcular as ferias de cada funcionario e descobrir o impacto que cada funcionario com ferias vencidas gera a empresa


"""

ferias['ds'] = ferias['salario'] * 2
ferias['ut'] = ferias['ds'] / 3
ferias['vf'] =  ferias['anos_ferias_vencidas'] * ferias['ds'] + ferias['ut']
ferias[ferias['anos_ferias_vencidas'] > 0].groupby(['nome','cargo','anos_ferias_vencidas'])['vf'].sum().sort_values(ascending=False).map('{:,.2f}'.format)

"""Vamos criar uma coluna para colocar os resultados a cima"""

import numpy as np

# Calculate intermediate cost columns
ferias['ds'] = ferias['salario'] * 2
ferias['ut'] = ferias['ds'] / 3
ferias['vf'] = ferias['anos_ferias_vencidas'] * ferias['ds'] + ferias['ut']

# Calculate the sum of 'vf' for overdue vacations, grouped by 'nome', 'cargo', and 'anos_ferias_vencidas'
vf_overdue_grouped_sum = ferias[ferias['anos_ferias_vencidas'] > 0].groupby(['nome','cargo','anos_ferias_vencidas'])['vf'].sum()

# Create a temporary MultiIndex from the original DataFrame for mapping
temp_multi_index = pd.MultiIndex.from_arrays(
    [ferias['nome'], ferias['cargo'], ferias['anos_ferias_vencidas']],
    names=['nome', 'cargo', 'anos_ferias_vencidas']
)

# Map the grouped sums back to the new column, filling NaN (for non-overdue or no match) with 0
ferias['Custo das férias'] = temp_multi_index.map(vf_overdue_grouped_sum).fillna(0)

# Apply formatting to the 'Custo das férias' column
ferias['Custo das férias'] = ferias['Custo das férias'].map('{:,.2f}'.format)

"""Totalizando"""

f"{ferias[ferias['anos_ferias_vencidas'] > 0]['vf'].sum():,.2f}"

ferias ['total custo'] = f"{ferias[ferias['anos_ferias_vencidas'] > 0]['vf'].sum():,.2f}"

"""Setor com maior custo em Férias"""

ferias.groupby('setor')['vf'].sum().sort_values(ascending=False).map('{:,.2f}'.format)

ferias ['setor maior custo'] = ferias.groupby('setor')['vf'].sum().sort_values(ascending=False).map('{:,.2f}'.format)

ferias.to_csv('dados_ferias.csv',index = False, sep = ';')
ferias.head()